### ISSUE TITLE
Update Job Titles

### ISSUE THREAD

**Issue by CannonLock** [PelicanPlatform/PelicanPlatform.github.io#1]
Need to go through and update peoples titles if need be. 

https://github.com/PelicanPlatform/PelicanPlatform.github.io/blob/main/src/app/team/team.json

**Comment by bbockelm** [comment]
Not sure if Rich/Matevz/Alja's titles are correct -- can you reach out?

**Comment by CannonLock** [comment]
Figured them all out at the meeting.
